import DiscordJS, { Intents } from 'discord.js'
import dotenv from 'dotenv'

dotenv.config()
const { Board, Led } = require("johnny-five");
const board = new Board();
const steamapi=require('steam-price-api')


var roastsx = [
    "Yo Mama so fat she sued Xbox 360 for guessing her weight.",
    "You're so fat that when you were diagnosed with a flesh eating bacteria - the doctors gave you 87 years to live.",
    "You're so fat you've got more chins than a Hong Kong phone book.",
    "Yo Mama so fat she's on both sides of the family.",
    "Yo Mama so fat that even Dora couldn't explore her.",
    "Yo Mama so fat that she doesn't need the internet; she's already world wide.",
    "You're so fat that when you farted you started global warming.",
    "You're so fat the back of your neck looks like a pack of hot-dogs.",
    "You're so fat that when you fell from your bed you fell from both sides.",
    "You're so fat when you get on the scale it says \"To be continued.\"",
    "You're so fat when you go swimming the whales start singing \"We Are Family\".",
    "You're so fat when you stepped on the scale, Buzz Lightyear popped out and said \"To infinity and beyond!\"",
    "You're so fat when you turn around, people throw you a welcome back party.",
    "You're so fat when you were in school you sat by everybody.",
    "You're so fat when you went to the circus the little girl asked if she could ride the elephant.",
    "You're so fat when you go on an airplane, you have to pay baggage fees for your ass.",
    "You're so fat whenever you go to the beach the tide comes in.",
    "You're so fat I could slap your butt and ride the waves.",
    "You're so fat I'd have to grease the door frame and hold a Twinkie on the other side just to get you through.",
    "Yo Mama so dumb I told her Christmas was around the corner and she went looking for it.",
    "You're so dumb it took you 2 hours to watch 60 minutes.",
    "Yo Mama so dumb she bought tickets to Xbox Live.",
    "You're so dumb that you thought The Exorcist was a workout video.",
    "You're so ugly that you went to the salon and it took 3 hours just to get an estimate.",
    "You're so ugly that even Scooby Doo couldn't solve that mystery.",
    "What is the weighted center between Planet X and Planet Y? Oh it's YOU!",
    ":eggplant: :eggplant: :eggplant:",
    "Your birth certificate is an apology letter from the condom factory.",
    "I wasn't born with enough middle fingers to let you know how I feel about you.",
    "You must have been born on a highway because that's where most accidents happen.",
    "I'm jealous of all the people that haven't met you.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
    "You bring everyone a lot of joy, when you leave the room.",
    "What's the difference between you and eggs? Eggs get laid and you don't.",
    "You're as bright as a black hole, and twice as dense.",
    "I tried to see things from your perspective, but I couldn't seem to shove my head that far up my ass.",
    "Two wrongs don't make a right, take your parents as an example.",
    "You're the reason the gene pool needs a lifeguard.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're so ugly, when you popped out the doctor said \"Aww what a treasure\" and your mom said \"Yeah, lets bury it.\"",
    "I have neither the time nor the crayons to explain this to you.",
    "You have two brains cells, one is lost and the other is out looking for it.",
    "How many times do I have to flush to get rid of you?",
    "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
    "You shouldn't play hide and seek, no one would look for you.",
    "Some drink from the fountain of knowledge; you only gargled.",
    "Roses are red violets are blue, God made me pretty, what happened to you?",
    "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
    "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
    "The last time I saw a face like yours I fed it a banana.",
    "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
    "Which sexual position produces the ugliest children? Ask your mother.",
    "If you really want to know about mistakes, you should ask your parents.",
    "At least when I do a handstand my stomach doesn't hit me in the face.",
    "If I gave you a penny for your thoughts, I'd get change.",
    "If I were to slap you, it would be considered animal abuse.",
    "Do you know how long it takes for your mother to take a crap? Nine months.",
    "What are you going to do for a face when the baboon wants his butt back?",
    "Well I could agree with you, but then we'd both be wrong.",
    "You're so fat, you could sell shade.",
    "It looks like your face caught on fire and someone tried to put it out with a hammer.",
    "You're not funny, but your life, now that's a joke.",
    "You're so fat the only letters of the alphabet you know are KFC.",
    "Oh my God, look at you. Was anyone else hurt in the accident?",
    "What are you doing here? Did someone leave your cage open?",
    "You're so ugly, the only dates you get are on a calendar.",
    "I can explain it to you, but I can't understand it for you.",
    "You are proof that God has a sense of humor.",
    "If you spoke your mind, you'd be speechless.",
    "Why don't you check eBay and see if they have a life for sale.",
    "If I wanted to hear from an asshole, I'd fart.",
    "You're so fat you need cheat codes to play Wii Fit",
    "You're so ugly, when you got robbed, the robbers made you wear their masks.",
    "Do you still love nature, despite what it did to you?",
    "You are proof that evolution CAN go in reverse.",
    "I'll never forget the first time we met, although I'll keep trying.",
    "Your parents hated you so much your bath toys were an iron and a toaster",
    "Don't feel sad, don't feel blue, Frankenstein was ugly too.",
    "You're so ugly, you scared the crap out of the toilet.",
    "It's kinda sad watching you attempt to fit your entire vocabulary into a sentence.",
    "I fart to make you smell better.",
    "You're so ugly you make blind kids cry.",
    "You're a person of rare intelligence. It's rare when you show any.",
    "You're so fat, when you wear a yellow rain coat people scream ''taxi''.",
    "I heard you went to a haunted house and they offered you a job.",
    "You look like a before picture.",
    "If your brain was made of chocolate, it wouldn't fill an M&M.",
    "Aww, it's so cute when you try to talk about things you don't understand.",
    "I heard your parents took you to a dog show and you won.",
    "You stare at frozen juice cans because they say, \"concentrate\".",
    "You're so stupid you tried to wake a sleeping bag.",
    "Am I getting smart with you? How would you know?",
    "We all sprang from apes, but you didn't spring far enough.",
    "I'm no proctologist, but I know an asshole when I see one.",
    "When was the last time you could see your whole body in the mirror?",
    "You must have a very low opinion of people if you think they are your equals.",
    "So, a thought crossed your mind? Must have been a long and lonely journey.",
    "You're the best at all you do - and all you do is make people hate you.",
    "Looks like you fell off the ugly tree and hit every branch on the way down.",
    "Looks aren't everything; in your case, they aren't anything.",
    "You have enough fat to make another human.",
    "You're so ugly, when you threw a boomerang it didn't come back.",
    "You're so fat a picture of you would fall off the wall!",
    "Your hockey team made you goalie so you'd have to wear a mask.",
    "Ordinarily people live and learn. You just live.",
    "Did your parents ever ask you to run away from home?",
    "I heard you took an IQ test and they said your results were negative.",
    "You're so ugly, you had tinted windows on your incubator.",
    "Don't you need a license to be that ugly?",
    "I'm not saying you're fat, but it looks like you were poured into your clothes and someone forgot to say \"when\"",
    "I've seen people like you, but I had to pay admission!",
    "I hear the only place you're ever invited is outside.",
    "Keep talking, someday you'll say something intelligent!",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "Even if you were twice as smart, you'd still be stupid!",
    "You're so fat, you have to use a mattress as a maxi-pad.",
    "I may be fat, but you're ugly, and I can lose weight.",
    "I was pro life before I met you.",
    "What's the difference between you and Hitler? Hitler knew when to kill himself.",
    "You're so fat, your double chin has a double chin.",
    "If ignorance is bliss, you must be the happiest person on earth.",
    "You're so stupid, it takes you an hour to cook minute rice.",
    "Is that your face? Or did your neck just throw up?",
    "You're so ugly you have to trick or treat over the phone.",
    "I'd hit you but we don't hit girls around here.",
    "Dumbass.",
    "Bitch.",
    "I'd give you a nasty look but you've already got one.",
    "If I wanted a bitch, I'd have bought a dog.",
    "Scientists say the universe is made up of neutrons, protons and electrons. They forgot to mention morons.",
    "Why is it acceptable for you to be an idiot but not for me to point it out?",
    "Did you know they used to be called \"Jumpolines\" until your mum jumped on one?",
    "You're not stupid; you just have bad luck when thinking.",
    "I thought of you today. It reminded me to take the garbage out.",
    "I'm sorry I didn't get that - I don't speak idiot.",
    "Hey, your village called \u2013 they want their idiot back.",
    "I just stepped in something that was smarter than you\u2026 and smelled better too.",
    "You're so fat that at the zoo the elephants started throwing you peanuts.",
    "You're so fat every time you turn around, it's your birthday.",
    "You're so fat your idea of dieting is deleting the cookies from your internet cache.",
    "You're so fat your shadow weighs 35 pounds.",
    "You're so fat I could tell you to haul ass and you'd have to make two trips.",
    "You're so fat I took a picture of you at Christmas and it's still printing.",
    "You're so fat I tried to hang a picture of you on my wall, and my wall fell over.",
    "You're so fat Mount Everest tried to climb you.",
    "You're so fat you can't even jump to a conclusion.",
    "You're so fat you can't fit in any timeline.",
    "You're so fat you can't fit in this joke.",
    "You're so fat you don't skinny dip, you chunky dunk.",
    "You're so fat you fell in love and broke it.",
    "You're so fat you go to KFC and lick other peoples' fingers.",
    "You're so fat you got arrested at the airport for ten pounds of crack.",
    "You're so fat you'd have to go to Sea World to get baptized.",
    "You're so fat you have your own zip code.",
    "You're so fat you have more rolls than a bakery.",
    "You're so fat you don't have got cellulite, you've got celluheavy.",
    "You're so fat you influence the tides.",
    "You're so fat you jumped off the Grand Canyon and got stuck.",
    "You're so fat that you laid on the beach and Greenpeace tried to push you back in the water.",
    "You're so fat you leave footprints in concrete.",
    "You're so fat you need GPS to find your asshole.",
    "You're so fat you pull your pants down and your ass is still in them.",
    "You're so fat you show up on radar.",
    "If you were any less intelligent we'd have to water you three times a week..",
    "If your IQ was 3 points higher, you'd be a rock.",
    "I would insult you but nature did a better job.",
    "Does your ass get jealous of all the shit that comes out of your mouth?",
    "If I ate a bowl of alphabet soup, I could shit out a smarter sentence than any of yours.",
    "You're not pretty enough to be this stupid.",
    "That little voice in the back of your head, telling you you'll never be good enough? It's right.",
    "You look like you're going to spend your life having one epiphany after another, always thinking you've finally figured out what's holding you back, and how you can finally be productive and creative and turn your life around. But nothing will ever change. That cycle of mediocrity isn't due to some obstacle. It's who you *are*. The thing standing in the way of your dreams is; that the person having them is *you*.",
    "May your day and future be as pleasant as you are.",
    "I would agree with you but then we would both be wrong.",
    "I bite my thumb at you, sir.",
    "I'd call you a tool, but that would imply you were useful in at least one way.",
    "I hope you outlive your children.",
    "Are you and your dick having a competition to see who can disappoint me the most?",
    "Yo mamma is so ugly her portraits hang themselves.",
    "Your birth certificate is an apology from the abortion clinic.",
    "If you were anymore inbred you'd be a sandwich.",
    "Say hello to your wife and my kids for me.",
    "You are thick-headed bastards with a bloated bureaucracy, designed to compensate for your small and poor self-esteem, cocksuckers. You have the brains to ban the person who has come to support channel your bot, accusing him of violating the ephemeral ephemeral rules, stupid morons. By the way i have one of the biggest server(5.5k  people, ~30 anytime voiceonline members), and i know something about managing, and of these rules - dont be an asshole. You are fucking asshole, maybe it is product of your life alone, or your life with your mom, anyway - you are retard and your soul is a fucking bunch of stupid self-esteems."
]; 

var complimentsx = [
    "Hey there sexy!",
    "I hope your day is as nice as your face!",
    "Have you been working out?",
    "I'm lucky to be your mirror!",
    "The Force is strong with you",
    "If I could high five you... I would!",
    "On a scale from 1 to 10, you're an 15!",
    "Being awesome is hard, but you'll manage",
    "I could just hang here all day!",
    "I need some time to reflect...",
    "I see a lot of myself in you",
    "Damn. You're looking good!",
    "Yes, you are the fairest of them all",
    "May the Force be with you",
    "There's no place like home",
    "There is no spoon...",
    "Temet Nosce",
    "Welcome to the desert of the real",
    "If you focus on what you’ve left behind, you will never be able to see what lies ahead",
    "I carried a watermelon",
    "You gotta hold the frame",
    "Never underestimate the power of denial",
    "Strangers all wanna sit next to you on the bus",
    "Coworkers fantasizes about getting stuck in the elevator with you",
    "At least two friends are going to name their child and/or goldfish after you",
    "You are freakishly good at thumb wars",
    "The FBI tapped your phone just to hear the sound of your voice",
    "You never forget to fill the ice-cube tray",
    "People enjoy you accidentally touching their butt while putting on your seat-belt",
    "I’d give you the last piece of my gum even if I’d just ate garlic",
    "You could make up a weird religion or diet and everyone would follow it",
    "Your principal would call you to the office just to look cool",
    "Your handshake conveys intelligence, confidence and minor claminess",
    "Cops admire your ability to stay a perfect 3-5 miles above the speed limit",
    "You rarely have to go to the bathroom when you fly in the window seat",
    "Cockroaches, mice and other pests avoid your place out of respect",
    "Callers are intimidated by how funny your voicemail greeting is",
    "Kids think you are the “cool old person”",
    "People always think your jeggings are regular jeans",
    "80% of motorcycle gangs think you’d be a delightful sidecar",
    "Everyone at the laundromat thinks you have the cutest underwear",
    "People behind you at movies think you are the perfect height",
    "Your parents argue over which one of them you look like",
    "Your smile is contagious",
    "You look great today",
    "You're a smart cookie",
    "I bet you make babies smile",
    "You have impeccable manners",
    "I like your style",
    "You have the best laugh",
    "I appreciate you",
    "You are the most perfect you there is",
    "Your perspective is refreshing",
    "You're an awesome friend",
    "You light up the room",
    "You deserve a hug right now",
    "You should be proud of yourself",
    "You're more helpful than you realize",
    "You have a great sense of humor",
    "You've got all the right moves!",
    "You're all that and a super-size bag of chips",
    "You're even more beautiful on the inside than you are on the outside",
    "If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now",
    "You are making a difference",
    "You're like sunshine on a rainy day",
    "You bring out the best in other people",
    "Your ability to recall random factoids at just the right time is impressive",
    "You're a great listener",
    "How is it that you always look great, even in sweatpants?",
    "Everything would be better if more people were like you!",
    "I bet you sweat glitter",
    "You were cool way before hipsters were cool",
    "That color is perfect on you",
    "Hanging out with you is always a blast",
    "You smell really good",
    "Being around you makes everything better!",
    "When you say, \"I meant to do that,\" I totally believe you",
    "Colors seem brighter when you're around",
    "You're wonderful",
    "You have cute elbows. For reals!",
    "Jokes are funnier when you tell them",
    "You're better than a triple-scoop ice cream cone. With sprinkles",
    "Your bellybutton is kind of adorable",
    "Your hair looks stunning",
    "You're one of a kind!",
    "You're inspiring",
    "You should be thanked more often. So thank you!!",
    "You have the best ideas",
    "You always know how to find that silver lining",
    "Everyone gets knocked down sometimes, but you always get back up and keep going",
    "You're a candle in the darkness",
    "You're a great example to others",
    "Being around you is like being on a happy little vacation",
    "You always know just what to say",
    "You're always learning new things and trying to better yourself, which is awesome",
    "If someone based an Internet meme on you, it would have impeccable grammar",
    "You could survive a Zombie apocalypse",
    "You're more fun than bubble wrap",
    "When you make a mistake, you fix it",
    "Who raised you? They deserve a medal for a job well done",
    "You're great at figuring stuff out",
    "Your voice is magnificent",
    "The people you love are lucky to have you in their lives",
    "You're like a breath of fresh air",
    "You're gorgeous -- and that's the least interesting thing about you, too",
    "You're so thoughtful",
    "Your creative potential seems limitless",
    "Your name suits you to a T",
    "You're irresistible when you blush",
    "Actions speak louder than words, and yours tell an incredible story",
    "Somehow you make time stop and fly at the same time",
    "When you make up your mind about something, nothing stands in your way",
    "You seem to really know who you are",
    "Any team would be lucky to have you on it",
    "In high school I bet you were voted \"most likely to keep being awesome.\"",
    "Babies and small animals probably love you",
    "You're someone's reason to smile",
    "You're even better than a unicorn, because you're real",
    "How do you keep being so funny and making everyone laugh?",
    "You have a good head on your shoulders",
    "Has anyone ever told you that you have great posture?",
    "The way you treasure your loved ones is incredible",
    "You're really something special",
    "You're a gift to those around you",
    "You're so smart! Why haven't I thought of that before?",
    "You look great in that outfit",
    "You look younger than your age",
    "I like the way you smile",
    "You're so funny!",
    "Thank you for being so thoughtful",
    "Did you lose some weight? You look healthy",
    "I like you because you are a great listener",
    "You inspired me to become a better person",
    "I couldn't have finished this project without your help",
    "I like your sense of style",
    "Your hair looks amazing",
    "You smell good today",
    "You rock that shirt!",
    "Good job!",
    "I like your shoes",
    "I like the way you designed my website",
    "You have a lovely voice",
    "Your sweater looks nice. Where did you buy that?",
    "You cracked me up with that joke",
    "I love all of the photos you've taken",
    "You are a great husband",
    "That's so awesome!",
    "Have been working out lately?",
    "How do you style your hair like that?",
    "I like your pants",
    "I will recommend your service to my friends",
    "You must be the life of the party",
    "You look even better without makeup",
    "You have a great taste in clothes",
    "Take a break! You deserve a vacation",
    "How do make your skin to look flawless and radiant?",
    "Nice nails!",
    "You are one of a kind",
    "You look cool in those boots",
    "Keep up the good work!",
    "You nailed it!",
    "Those shoes were a great call. ",
    "9/10 dentists agree, you are the BEST",
    "Today's outfit = Thumbs up",
    "Your hair looks great today. It also looked really good two days ago",
    "You could be an astronaut if you wanted. NASA told me so",
    "Your dental hygiene is impeccable.  ",
    "8 out of 10 co-workers agree, your desk is the cleanest. ",
    "You'd be the last one standing in a horror movie",
    "You're funny. Like, LOL style",
    "You have very smooth hair",
    "You deserve a promotion",
    "I like your style",
    "That looks nice on you",
    "You have perfect bone structure",
    "I like your socks",
    "Your smile is breath taking",
    "You make my data circuits skip a beat",
    "You are the gravy to my mashed potatoes",
    "You're cooler than Pirates and Ninjas combined",
    "I like your pants",
    "You could probably lead a rebellion",
    "Your skin is radiant",
    "You could survive a zombie apocalypse",
    "You're so rad",
    "You're more fun than a barrel of monkeys",
    "You're nicer than a day on the beach",
    "Your glass is the fullest",
    "You look so perfect",
    "You're more fun than bubble wrap",
    "You're the bee's knees",
    "You definitely know the difference between your and you're",
    "Yum!, I dig you",
    "You got the moves like Jagger",
    "I would volunteer to take your place in the Hunger Games",
    "You have such nice eyes",
    "You're awesome",
    "You're the best",
    "You're fantastic",
    "You're really flipping smart",
    "You look awesome today, seriously"
];
const client = new DiscordJS.Client({
    intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES
    ]
})

board.on("ready", function(){
    client.on('ready', () => {
        console.log('bot deployed');
    })
    client.on('messageCreate',(message)=>{
        console.log(message.content);
        if (message.content=='.ping') {
            message.reply('ponggggg');
        } 
        if (message.content==".insultme"){
            var roasty = roastsx[Math.floor(Math.random() * roastsx.length)];
            message.reply(roasty);
        }
        if (message.content==".complimentme"){
            var comlpimentsY = complimentsx[Math.floor(Math.random() * complimentsx.length)];
            message.reply(comlpimentsY);
        }
        const led = new Led(13);
        if (message.content==".turnLedOn")
        {
            led.on();
            message.reply("LED is ON");
        }
        if (message.content==".turnLedOff")
        {
            led.off();
            message.reply("LED is OFF");
        }
        if (message.content.startsWith(".ledBrightness")){
            var brightx=message.content.slice(14)
            led.brightness(parseInt(brightx))
            console.log("gg")
        }
    })
});
client.login(process.env.TOKEN)